name: Sync Fork
on:
#   schedule:
#     - cron: '0 0 * * *'
  workflow_dispatch: # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Crucial for finding the common history
        # Add this step to configure the Git user
      - name: Configure Git user
        run: |
          git config --global user.email "little_tor@hotmail.com"
          git config --global user.name "noppadol-assava"
      - name: Sync upstream
        run: |
          git remote add upstream https://github.com/itskovacs/trip
          git fetch upstream --tags
          git checkout main
          git merge upstream/main -m "Merge upstream changes"
          git push origin main
          git push origin --tags
